################################# Todo #############################################
POST http://localhost:5000/api/item 
content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzdmYmYwMmJlM2M5YTFhODczOWQ4ZjAiLCJlbWFpbCI6InJhaXlhbjA3QGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg3NzU3NDczLCJleHAiOjE2ODc3NjEwNzN9.oCCAjeKKRyMBvuwYTfiHG7ZyZu_EVPWT33UCqlXW0ZA

{
    "item": "Buy Desktop PC"
}

### Create Item ↑↑

GET http://localhost:5000/api/items
content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzdmYmYwMmJlM2M5YTFhODczOWQ4ZjAiLCJlbWFpbCI6InJhaXlhbjA3QGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg3NzU3NDczLCJleHAiOjE2ODc3NjEwNzN9.oCCAjeKKRyMBvuwYTfiHG7ZyZu_EVPWT33UCqlXW0ZA


### Get Items ↑↑

GET http://localhost:5000/api/items/6390b6514f1796d6e64e4972
content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzdmYmYwMmJlM2M5YTFhODczOWQ4ZjAiLCJlbWFpbCI6InJhaXlhbjA3QGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg3NzU3NDczLCJleHAiOjE2ODc3NjEwNzN9.oCCAjeKKRyMBvuwYTfiHG7ZyZu_EVPWT33UCqlXW0ZA


### Get An Item ↑↑

PUT http://localhost:5000/api/item/6390b6514f1796d6e64e4972
content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzdmYmYwMmJlM2M5YTFhODczOWQ4ZjAiLCJlbWFpbCI6InJhaXlhbjA3QGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg3NzU3NDczLCJleHAiOjE2ODc3NjEwNzN9.oCCAjeKKRyMBvuwYTfiHG7ZyZu_EVPWT33UCqlXW0ZA

{
    "item": "Vung Vang", 
    "complete": false
}

 
### Update an Item ↑↑

DELETE  http://localhost:5000/api/item/6383bcff44571b24da99fa1b
content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzdmYmYwMmJlM2M5YTFhODczOWQ4ZjAiLCJlbWFpbCI6InJhaXlhbjA3QGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg3NzU3NDczLCJleHAiOjE2ODc3NjEwNzN9.oCCAjeKKRyMBvuwYTfiHG7ZyZu_EVPWT33UCqlXW0ZA


### Delete an Item ↑↑

################################ Montly Sheets ##########################################

POST http://localhost:5000/api/MonthlySheet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzFhMzg1ZjhmN2EyY2Y4NWM5ZDk1OWQiLCJlbWFpbCI6InJhaXlhbjE1QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImFjbCI6WyJ0b2RvIiwibm90ZXMiLCJkYWlseS1yZXBvcnQiLCJjcm0iLCJpbnZlbnRvcnkiLCJxdWlja2llIl0sImlhdCI6MTcyOTc3MTY0MSwiZXhwIjoxNzI5ODU4MDQxfQ.KTywLxQTav5DC75FXc5G9op-x7DbR19bITvoqjCx4_k

{
    "month_name": "April",
    "starting_balance": 6500
}

## Create Monthly Sheet

GET http://localhost:5000/api/MonthlySheet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzFhMzg1ZjhmN2EyY2Y4NWM5ZDk1OWQiLCJlbWFpbCI6InJhaXlhbjE1QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImFjbCI6WyJ0b2RvIiwibm90ZXMiLCJkYWlseS1yZXBvcnQiLCJjcm0iLCJpbnZlbnRvcnkiLCJxdWlja2llIl0sImlhdCI6MTcyOTc3MTY0MSwiZXhwIjoxNzI5ODU4MDQxfQ.KTywLxQTav5DC75FXc5G9op-x7DbR19bITvoqjCx4_k



GET http://localhost:5000/api/MonthlySheet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzFhMzg1ZjhmN2EyY2Y4NWM5ZDk1OWQiLCJlbWFpbCI6InJhaXlhbjE1QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImFjbCI6WyJ0b2RvIiwibm90ZXMiLCJkYWlseS1yZXBvcnQiLCJjcm0iLCJpbnZlbnRvcnkiLCJxdWlja2llIl0sImlhdCI6MTcyOTc3MTY0MSwiZXhwIjoxNzI5ODU4MDQxfQ.KTywLxQTav5DC75FXc5G9op-x7DbR19bITvoqjCx4_k

################################ AUTH ##########################################

POST http://localhost:5000/api/user/registration
content-Type: application/json

{
    "fullname": "Shahadat Raiyan",
    "email": "raiyan12@gmail.com",
    "naam": "raiyan12",
    "password": "1@qQasdf"
}

### User Registration Regular ↑ // note and todo

POST http://localhost:5000/api/user/registration/daily-report
content-Type: application/json

{
    "fullname": "Shahadat Raiyan",
    "email": "raiyan12@gmail.com",
    "naam": "raiyan12",
    "password": "1@qQasdf"
}

### User Registration Daily Report ↑

POST http://localhost:5000/api/user/registration/admin
content-Type: application/json

{
    "fullname": "Shahadat Admin",
    "email": "raiyan15@gmail.com",
    "naam": "raiyan15",
    "password": "1@qQasdf"
}

### Admin Registration ADMIN ↑

DELETE http://localhost:5000/api/user/637e68d770ce03fc24e52cd8
content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzhhZGI2N2Y4MmQxMDkzODk1NzE1MDQiLCJlbWFpbCI6InNocmFpeWFuMjFAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiYWNsIjpbInRvZG8iLCJub3RlcyIsImRhaWx5LXJlcG9ydCIsImNybSIsImludmVudG9yeSJdLCJpYXQiOjE3MDg4OTE1NzUsImV4cCI6MTcwODk3Nzk3NX0.pXl8A7BBLYzntfC3udMoMW25QeQqCob4DwcbHYFwi5I

### User Delete // Only by admin ↑

GET http://localhost:5000/api/user/6388563fe7c0712c7ac14326
content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzhhZGI2N2Y4MmQxMDkzODk1NzE1MDQiLCJlbWFpbCI6InNocmFpeWFuMjFAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiYWNsIjpbInRvZG8iLCJub3RlcyIsImRhaWx5LXJlcG9ydCIsImNybSIsImludmVudG9yeSJdLCJpYXQiOjE3MDg4OTE1NzUsImV4cCI6MTcwODk3Nzk3NX0.pXl8A7BBLYzntfC3udMoMW25QeQqCob4DwcbHYFwi5I


### Get Single User // Only by admin ↑

GET http://localhost:5000/api/users
content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzhhZGI2N2Y4MmQxMDkzODk1NzE1MDQiLCJlbWFpbCI6InNocmFpeWFuMjFAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiYWNsIjpbInRvZG8iLCJub3RlcyIsImRhaWx5LXJlcG9ydCIsImNybSIsImludmVudG9yeSJdLCJpYXQiOjE3MDg4OTE1NzUsImV4cCI6MTcwODk3Nzk3NX0.pXl8A7BBLYzntfC3udMoMW25QeQqCob4DwcbHYFwi5I

### Get All User // Only by admin ↑

### user 1
POST http://localhost:5000/api/login
content-Type: application/json

{
    "email": "raiyan15@gmail.com",
    "password": "1@qQasdf"
}